### PR TITLE
technical-writing-seminar-redux

### PR DESCRIPTION
**Pull request by kghamilton89**
This is an Axibase-flavored version of the Google Style Guides. I've noted the topics that I mentioned [here](https://nur.axibase.com:41791/redmine/issues/5354) that I was unable to resolve myself so that we can focus group them at the workshop.

I left off a few sections from GSG that weren't relevant to us, and re-organized their structure a bit to better suit our needs.

### CODE REVIEW

**Comment by kghamilton89** [comment]
* Redmine add-on.

**Comment by kghamilton89** [comment]
* A few edits for flow and grammar.

**Comment by kghamilton89** [comment]
Edits based on the decisions made during the seminar:
* Specific **Fenced Text** section added.
* Rule changed: we no longer fence HTTP request methods.
* Interface elements section updated.
* Parentheses and quotation marks sections updated to show that we want to henceforth avoid them.

**Comment by rodionos** [comment]
This is a great summary. I'd like to trim it down to only show section where a) we differ from the the google guide or b) their guide needs clarification. Lets make this document a cheat sheet, a brief reference, as concise as possible. I suggest the following structure. If we agree with GDSG, just add "Same as GDSG" and link to the article. Example:

## Abbreviations

Same as [GDSG](https://developers.google.com/style/abbreviations).

* Abbreviate if the acronym is familiar to the target audience. 
* Do not backtick acronyms.
* Use "for example" instead of "i.e." or "e.g.";

Known acronyms (always use):  CSV, JSON, XLS, XML, XLS (other data formats), SQL, API, HTTP, REST, JVM.

If the acronym is new but is used multiple times in the article,  introduce it once in the beginning and re-use thereafter.

"Axibase Time Series Database (ATSD) is a non-relational database."

**Comment by rodionos** [comment]
## Headings

* Use title case.
* Avoid words that need backticking in headings.
* Do not apply backticks in headings (if necessary ad word to dictionary).
* Do not use dots, commas, brackets and other punctuation symbols in headings.
 
## Backticks

Apply single backticks to:

* File names
* Program names
* HTTP methods
* API endpoint paths (or use code blocks for single line paths).
* Parameter names, field names, variables

Exceptions:

* Do not use backtick words inside the headings.

So based on these rules, the curl must be backticked in collector repo:

If `wget` is not installed, use curl:

**Comment by kghamilton89** [comment]
Yeah the `curl` question was still live yesterday. I know there aren't too many occurrences in Collector repo so it will be a quick fix.

**Comment by rodionos** [comment]
I'd like to refactor this article into a reference document. Really concise sets of rules, for example:

image

No need to explain 'why'. Just spell out our requirement with minimal example, if necessary,

**Comment by rodionos** [comment]
I have prepared three section example: Heading, Abbreviations, Backticks to use as a template. No need to repeat google guideline if we fully agree with it.

**Comment by kghamilton89** [comment]
* Sections which do not meaningfully deviate from Google Style Guides removed.
* Examples and explanations removed, unless needed.
* Style refactored to be bullet-pointed.

**Comment by kghamilton89** [comment]
* Added GDG links where appropriate.
* Expanded requested sections. 
* Added examples where needed.

**Pull request merged**
