### PR TITLE
time-zones-seminar

### PR DESCRIPTION
**Pull request by kghamilton89**
Time zones seminar document.

### CODE REVIEW

**Comment by rodionos** [comment]
We're several weeks from the presentation date, so there is enough time to perform some interesting analysis.

For instance, what are the places (cities) with the most dislocation from their natural time.

> Local mean solar time depends upon longitude; it is advanced by four minutes per degree eastward. 

* SFO: 37°47′N 122°25′W
* NYC: 40°42′46″N 74°00′21″W

```
122.25-74 = 48.25 longitude degrees * 4 minutes = 193 minutes = 3 hours 13 minutes
```

So SFO is 13 minutes too early. This assumes that NYC is 'on-time' which may not be the case. Research what is the correct natural time and ideally calculate the difference for the biggest cities.
It is a known fact that misconfigured circadian clocks cause a lot of damage, including in students, e.g. https://www.independent.co.uk/news/education/education-news/ban-9am-lectures-for-students-circadian-rhythms-11am-lecture-body-clocks-open-nevada-university-a7675291.html

**Comment by kghamilton89** [comment]
Sounds great. I didn't want to take up an inordinate amount of time for the presentation to occupy.

**Comment by rodionos** [comment]
If we can load latitude, longitude, and timezone as series into ATSD, we can then analyze a) pairs of cities to find out which cities have the largest difference between their coordinates and civil time and b) which cities have the largest difference between administrative time and solar time.

Collect the following data set for cities:

```
City Name,Country,Latitude,Longitude,Time zone name,GMT offset in minutes
```

GMT offset in minutes should be without DST.

If there are population numbers available, that would be useful too. Try locating data for cities with over 1+ mln population.

**Comment by kghamilton89** [comment]
At the moment, the bulk of the work is done. I'm waiting for the resolution of the trig functions ticket and I will perform the latter of the two experiments in SQL Console instead of approximating them via visualization.

**Comment by kghamilton89** [comment]
Using SQL margin of error is significantly less than visualization. I imagine this has to do with the precision of using SQL instead of what amounts to visually estimating value. ATSD produced results with &lt; 1.0% margin of error.

**Comment by rodionos** [comment]
Interesting subjects to cover:

1) Which international bodies maintain TZ databases.
2) How about time zones on other planets (e.g. see tzdata2018g/theory.html - last section in http://www.iana.org/time-zones)

Also, it would be useful to briefly discuss the latest time zone changes in major countries (pros and cons):

1) DST abolished in Russia (2013/2014?)
2) DST is expected to be abolished in the E.U.
3) DST changes currently discussed in the U.S. - https://www.timeanddate.com/news/time/usa-states-no-dst.html. Perhaps a reference to reasons provided in one of the state bills would be useful
4) Australia DST changes a while ago.

**Pull request merged**
