### PR TITLE
breakeven-rate

### PR DESCRIPTION
**Pull request by kghamilton89**
Chart of the Day which uses a bunch of Fred data to track how quickly Inflation and CPI are outstripping real wage growth.

### CODE REVIEW

**Comment by rodionos** [comment]
This is a great topic as inflation in the US picks up but wages are lagging in 'real terms' as it's called.

* No need to install or download: use Trends for all tasks
* Show how any series can be adjusted by inflation by subtracting inflation from the rate of change: wages, tax revenues, any monetary measure.
* Add chart screenshots - I couldn't find any.

**Comment by kghamilton89** [comment]
@rodionos Data needs to be uploaded to Trends. Who should I assign the ticket to? I don't know what happened to the screenshots... I saw them just fine yesterday, I'll re-upload them.

**Comment by rodionos** [comment]
Fred series should already be in Trends. Which series are we missing?

**Comment by kghamilton89** [comment]
* DGS10
* DFII10

**Pull request closed without merging**
