### PR TITLE
Bot

### PR DESCRIPTION
**Pull request by annstriganova**

### CODE REVIEW

**Comment by annstriganova** [comment]
There are two typos, I think they should be ignored:

```java
0.93s$ spellcheck --single
✗ /home/travis/build/axibase/atsd-use-cases/workshop/trends-bot.md 461 ms
-----
Typos: 2
1. JSONs (211:12, count: 2, suggest: Jones, Sons, Json, Jeans, Sans)
2. adj (suggest: ads, dj)
-----
```

**Comment by annstriganova** [comment]
There are two typos, I think they should be ignored:

```java
0.93s$ spellcheck --single
✗ /home/travis/build/axibase/atsd-use-cases/workshop/trends-bot.md 461 ms
-----
Typos: 2
1. JSONs (211:12, count: 2, suggest: Jones, Sons, Json, Jeans, Sans)
2. adj (suggest: ads, dj)
-----
```

**Comment by rodionos** [comment]
Better: JSON documents or JSON files, or JSON objects.
What is adj?

**Comment by rodionos** [comment]
As a first step, move the series search logic to python script using our ATSD API python. It should a) improve the rule's readability and b) allow you to implement a custom search logic in python code.

**Comment by annstriganova** [comment]
```
$ spellcheck --single
✗ /home/travis/build/axibase/atsd-use-cases/workshop/trends-bot.md 350 ms
-----
Typos: 1
1. adj (suggest: ads, dj)
-----
```
It seems that `seasonal_adj_list` and etc. matched.

**Comment by annstriganova** [comment]
`search_metrics.py` can be simplified by replacing message querying with `last_open()` function. Should I try to do it?

**Comment by rodionos** [comment]
> search_metrics.py

Yes, try simplifying it using the last_open function.

**Comment by annstriganova** [comment]
No message attachments sent by Rule Engine created dynamically according to tags selected by user, so there is no scenario when "No metrics are found. Try again." 

There are two open questions:

**1)** due to date in response, dialog looks like this:
selection_095
Instead of this:
trends_bot_7
I can't find setting in Slack docs preventing from replacing interactive component with server response, [`"replace_original":false`](https://api.slack.com/docs/interactive-message-field-guide) doesn't work.


**2)** I think it would be better to replace this image, it looks sloppy, but I need an advice how better to display the interaction between ATSD and Slack.
  
trends_bot_6

**Comment by annstriganova** [comment]
Interesting, but there is no practical application. Also, the Slack API has changed significantly, so it's too difficult to make it work.

**Pull request closed without merging**
