### PR TITLE
minor-refactor

### PR DESCRIPTION
**Pull request by kghamilton89**
* Many of the bullet points were missing punctuation, so I added it.
* Added a section called **Time** listing our time rules (use 24-hour format or Unix Time if needed).
* Alphabetized sections.

### CODE REVIEW

**Comment by kghamilton89** [comment]
@raipc many blacklisted words and other lint appears in this document as examples of what not to do. Thus, Travis build continues to fail.

**Comment by kghamilton89** [comment]
I guess, you can confirm that there are no "real" errors here and add this file to skip list.

**Comment by rodionos** [comment]
The order of sections is important. We need to finalize the guide before changing the order.

**Comment by kghamilton89** [comment]
What about blacklisted words and style rules that are causing the build to fail?

**Comment by kghamilton89** [comment]
Commit `emoji-repair`: one set of emojis was applied to the opposite fields.

**Pull request merged**
