### PR TITLE
How To Shared Import Files

### PR DESCRIPTION
**Pull request by kghamilton89**
Please ignore the branch name, it was a typo. This article discusses uploading an entity view.

### CODE REVIEW

**Comment by rodionos** [comment]
It's better to import the portal by attaching the XML file, not by creating a new portal by hand and copy-pasting the content.

**Comment by kghamilton89** [comment]
This PR contains the following articles for the how-to/shared folder:

* Portals
* Entity Views
* CSV Parsers
* Entity Groups
* Tag Templates
* Rules
* Scheduled SQL Queries

**Comment by rodionos** [comment]
The entity groups are imported via Settings: Entity Groups: Import. Modify import-entity-groups.md accordingly. Also, add md file for how to import entities and how to import metrics. Link to ATSD documentation in the Overview section of each file, where appropriate. For example, importing EG document can refer to https://github.com/axibase/atsd/blob/master/configuration/entity_groups.md

**Comment by rodionos** [comment]
Also, I would add a tip/hint at the end of each import document, that if the user has multiple files to import, they can upload them individually or as an archive on `Settings>Diagnostics>Backup Import`.

**Comment by kghamilton89** [comment]
For my own use:

An Entity Group represents a collection of entities, typically grouped by a common feature or an attribute. The groups typically consist of entities of similar type, such as 'Docker Containers', or entities collecting the same metrics, such as 'collectd' agents.

**Pull request merged**
