### PR TITLE
New use case

### PR DESCRIPTION
**Pull request by kghamilton89**

### CODE REVIEW

**Comment by kghamilton89** [comment]
An analysis of the current low interest rate, but rising debt market value environment.

**Comment by rodionos** [comment]
For  this article and going forward, lets try to make the leading chart a power chart. It has to be awesome from a graphical prospective so we can show off cool time chart features. The first chart is going to be a power chart, the others can be regular charts.

**Comment by rodionos** [comment]
Also, try using branch names that correspond to the subject of the article, e.g. fed-interest-rate-debt-bubble.

**Comment by kghamilton89** [comment]
In the Sources section there is a portal which has a ton of data from the article, would you like to use that in this case or maybe some already existing chart from the article?

**Comment by rodionos** [comment]
The chart in Sources is nice, but it's still a collection of 5 charts with basic graphical features. I'm thinking of one chart with baselines, alerts, combination of line+column, thresholds, or even visual tricks such as 2nd chart here: https://github.com/axibase/atsd-use-cases/tree/master/ChicagoCrime

**Comment by kghamilton89** [comment]
How do you feel about something like this?

https://apps.axibase.com/chartlab/a4da9436

**Comment by kghamilton89** [comment]
Or here's one that also includes a statistic = wtavg expression as well. For some reason, the purple fed rate line isn't showing up on my machine, but I'm sure that's local. 

https://apps.axibase.com/chartlab/a4da9436/6/

**Pull request merged**
