### PR TITLE
cloud-oktas

### PR DESCRIPTION
**Pull request by kghamilton89**
* Refactor and migration of [Measuring Cloud Oktas from Outer Space](https://axibase.com/calculating-cloud-oktas/).
* This is definitely a candidate for `/research` directory, so I kept it there.
* There is a small problem, which is that some of the [series](https://nur.axibase.com/metrics/metric.xhtml?metricName=bom.gov.au.cloud_oktas) used in this article have a **Retention Interval** of only 60 days, meaning some data has been removed from NUR. I think it's still worth publishing though, because the article is really interesting and the visualizations display the once-existent data.

### CODE REVIEW

**Comment by kghamilton89** [comment]
* `README.md` updated to include **Measuring Cloud Oktas From Outer Space**.
* `2015.md` created to account for publishing date.
* "nm", "oce", "EBImage" added to dictionary.
* Lint removal.

**Comment by kghamilton89** [comment]
* Since cloud cover and satellite data has already been pruned from the source and ATSD, what should we do about broken visualization?
* Build is failing because of the presence of words "true" and "top" both of which appear on the backticked words list.
* Broken anchor to former `/archive` directory removed from `README.md`

**Comment by rodionos** [comment]
There is new power usage data - https://apps.axibase.com/chartlab/8e2917e2/7/, but the satellite analysis data is not present for the same period. Remove links to Chartlab, keep only the screenshots.

**Comment by kghamilton89** [comment]
Links to portals removed.

**Pull request merged**
